example1:
  Proj_outchannel: 3
  b0: "None"
  b1: "Conv"
  b2: "Conv"
  b1_Conv_channels_0: 4
  b1_Conv_channels_1: 5
  b1_Conv_kernels_0: 1
  b1_Conv_kernels_1: 3
  b1_Conv_norms_0: "batch"
  b1_Conv_norms_1: null
  b1_Conv_acts_0: "ReLU"     
  b1_Conv_acts_1: "LeakyReLU" 
  b2_Conv_channels_0: 1
  b2_Conv_channels_1: 1
  b2_Conv_kernels_0: 3
  b2_Conv_kernels_1: 3
  b2_Conv_norms_0: null
  b2_Conv_norms_1: null
  b2_Conv_acts_0: "LeakyReLU"  
  b2_Conv_acts_1: "LeakyReLU" 
  MLP_width_0: 1
  MLP_width_1: 2
  MLP_width_2: 4
  MLP_acts_0: "Identity"      
  MLP_acts_1: "Identity"      
  MLP_acts_2: "LeakyReLU"      
  MLP_acts_3: "ReLU"         
  MLP_norms_0: "batch"
  MLP_norms_1: "batch"
  MLP_norms_2: "batch"
  MLP_norms_3: null

example2:
  Proj_outchannel: 0
  b0: "Conv"
  b1: "Conv"
  b2: "Conv"
  b0_Conv_channels_0: 5
  b0_Conv_channels_1: 4
  b0_Conv_kernels_0: 3
  b0_Conv_kernels_1: 3
  b0_Conv_norms_0: "batch"
  b0_Conv_norms_1: "batch"
  b0_Conv_acts_0: "ReLU"      
  b0_Conv_acts_1: "ReLU"      
  b1_Conv_channels_0: 2
  b1_Conv_channels_1: 2
  b1_Conv_kernels_0: 3
  b1_Conv_kernels_1: 3
  b1_Conv_norms_0: "batch"
  b1_Conv_norms_1: "batch"
  b1_Conv_acts_0: "LeakyReLU" 
  b1_Conv_acts_1: "LeakyReLU"  
  b2_Conv_channels_0: 2
  b2_Conv_channels_1: 2
  b2_Conv_kernels_0: 1
  b2_Conv_kernels_1: 3
  b2_Conv_norms_0: "batch"
  b2_Conv_norms_1: "batch"
  b2_Conv_acts_0: "GELU"      
  b2_Conv_acts_1: "ReLU"       
  MLP_width_0: 1
  MLP_width_1: 4
  MLP_width_2: 3
  MLP_acts_0: "ReLU"         
  MLP_acts_1: "GELU"         
  MLP_acts_2: "ReLU"         
  MLP_acts_3: "ReLU"         
  MLP_norms_0: null
  MLP_norms_1: "batch"
  MLP_norms_2: "batch"
  MLP_norms_3: null

## Example 3
example3:
  Proj_outchannel: 2
  b0: "Conv"
  b1: "None"
  b2: "Conv"
  b0_Conv_channels_0: 2
  b0_Conv_channels_1: 2
  b0_Conv_kernels_0: 1
  b0_Conv_kernels_1: 1
  b0_Conv_norms_0: null
  b0_Conv_norms_1: null
  b0_Conv_acts_0: "Identity"   
  b0_Conv_acts_1: "Identity"  
  b2_Conv_channels_0: 1
  b2_Conv_channels_1: 4
  b2_Conv_kernels_0: 1
  b2_Conv_kernels_1: 1
  b2_Conv_norms_0: "batch"
  b2_Conv_norms_1: "batch"
  b2_Conv_acts_0: "ReLU"     
  b2_Conv_acts_1: "ReLU"      
  MLP_width_0: 1
  MLP_width_1: 2
  MLP_width_2: 3
  MLP_acts_0: "GELU"        
  MLP_acts_1: "ReLU"         
  MLP_acts_2: "GELU"        
  MLP_acts_3: "ReLU"        
  MLP_norms_0: "batch"
  MLP_norms_1: "batch"
  MLP_norms_2: "batch"
  MLP_norms_3: null

## OpenHLS
openhls:
  b0: "ConvAttn"
  b1: "Conv"
  b2: "None"
  Proj_outchannel: 1
  b0_ConvAttn_hiddenchannel: 3
  b0_ConvAttn_act: "ReLU"    
  b1_Conv_channels_0: 2
  b1_Conv_channels_1: 0
  b1_Conv_kernels_0: 3
  b1_Conv_kernels_1: 3
  b1_Conv_acts_0: "ReLU"     
  b1_Conv_acts_1: "ReLU"     
  b1_Conv_norms_0: null
  b1_Conv_norms_1: null
  MLP_width_0: 2
  MLP_width_1: 1
  MLP_width_2: 0
  MLP_acts_0: "ReLU"        
  MLP_acts_1: "ReLU"        
  MLP_acts_2: "ReLU"         
  MLP_acts_3: "ReLU"       
  MLP_norms_0: null
  MLP_norms_1: null
  MLP_norms_2: null
  MLP_norms_3: null

## BraggNN
braggnn:
  b0: "ConvAttn"
  b1: "Conv"
  b2: "None"
  Proj_outchannel: 3
  b0_ConvAttn_hiddenchannel: 5
  b0_ConvAttn_act: "GELU"    
  b1_Conv_channels_0: 4
  b1_Conv_channels_1: 2
  b1_Conv_kernels_0: 3
  b1_Conv_kernels_1: 3
  b1_Conv_acts_0: "GELU"     
  b1_Conv_acts_1: "GELU"    
  b1_Conv_norms_0: null
  b1_Conv_norms_1: null
  MLP_width_0: 4
  MLP_width_1: 3
  MLP_width_2: 2
  MLP_acts_0: "GELU"        
  MLP_acts_1: "GELU"         
  MLP_acts_2: "GELU"        
  MLP_acts_3: "Identity"    
  MLP_norms_0: null
  MLP_norms_1: null
  MLP_norms_2: null
  MLP_norms_3: null
